version: "2"

services:
 mysqldb:
   image: mysql:5.7
   restart: unless-stopped
   environment:
     - MYSQL_DATABASE=dbachat
     - MYSQL_ALLOW_EMPTY_PASSWORD=true
   ports:
      - "3306:3306"
   volumes:
      - db:/var/lib/mysql
 app: 
   container_name: spring
   image: ademng/achat
   depends_on:
     - mysqldb
   build: .
   restart: on-failure
   ports:
     - "8089:8089"
   

